core/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index', ),
    url(r'^login$', views.login, name='login'),
    url(r'^logout$', views.logout, name='logout'),
]

webzmap/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from core.models import Job, WhiteListFile, BlackListFile, Command
from rest_framework import routers, serializers, viewsets


# Serializers define the API representation.
class JobSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = Job
        fields = (
            'url', 'id', 'name', 'port', 'subnets', 'status', 'bandwidth', 'verbosity', 'priority', 'creation_time',
            'pid',
            'read_time',
            'time_elapsed',
            'time_remaining', 'percent_complete', 'active_send_threads', 'sent_total', 'sent_last_one_sec',
            'sent_avg_per_sec', 'recv_success_total', 'recv_success_last_one_sec', 'recv_success_avg_per_sec',
            'recv_total',
            'recv_total_last_one_sec', 'recv_total_avg_per_sec', 'pcap_drop_total', 'drop_last_one_sec',
            'drop_avg_per_sec',
            'sendto_fail_total', 'sendto_fail_last_one_sec', 'sendto_fail_avg_per_sec', 'white_list_file',
            'black_list_file')
        # fields = '__all__'
        # exclude = ('output_path', 'log_path', 'status_path')
        read_only_fields = (
            'id', 'status', 'creation_time', 'pid', 'read_time', 'time_elapsed', 'time_remaining', 'percent_complete',
            'active_send_threads', 'sent_total', 'sent_last_one_sec', 'sent_avg_per_sec',
            'recv_success_total',
            'recv_success_last_one_sec', 'recv_success_avg_per_sec', 'recv_total',
            'recv_total_last_one_sec',
            'recv_total_avg_per_sec', 'pcap_drop_total', 'drop_last_one_sec', 'drop_avg_per_sec',
            'sendto_fail_total', 'sendto_fail_last_one_sec', 'sendto_fail_avg_per_sec')


class WhiteListFileSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = WhiteListFile
        fields = "__all__"
        read_only_fields = ('size',)
        extra_kwargs = {'file': {'write_only': True}}


class BlackListFileSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = BlackListFile
        fields = "__all__"
        read_only_fields = ('size',)
        extra_kwargs = {'file': {'write_only': True}}


class CommandSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = Command
        fields = "__all__"
        read_only_fields = ('creation_time',)


# ViewSets define the view behavior.
class JobViewSet(viewsets.ModelViewSet):
    queryset = Job.objects.all().order_by('-creation_time')
    serializer_class = JobSerializer


class WhiteListFileViewSet(viewsets.ModelViewSet):
    queryset = WhiteListFile.objects.all()
    serializer_class = WhiteListFileSerializer


class BlackListFileViewSet(viewsets.ModelViewSet):
    queryset = BlackListFile.objects.all()
    serializer_class = BlackListFileSerializer


class CommandViewSet(viewsets.ModelViewSet):
    queryset = Command.objects.all()
    serializer_class = CommandSerializer


# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'jobs', JobViewSet)
router.register(r'whitelistfiles', WhiteListFileViewSet)
router.register(r'blacklistfiles', BlackListFileViewSet)
router.register(r'commands', CommandViewSet)

urlpatterns = [
    url(r'^', include("core.urls", namespace="core")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

templates/base.html
<!DOCTYPE html>{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}WebZmap{% endblock %}</title>
    <link type="text/css" rel="stylesheet" media="screen" charset="UTF-8" href="//cdn.bootcss.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.10.0/css/bootstrap-select.min.css">

    <link rel="icon" href="{% static 'img/icon.png' %}"/>
    <style>
        body {
          padding-top: 60px;
        }
    </style>
</head>
<body>
{% block body %}{% endblock %}
<script charset="UTF-8" src="//cdn.bootcss.com/jquery/2.2.1/jquery.min.js"></script>
<script charset="UTF-8" src="//cdn.bootcss.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<script charset="UTF-8" src="//cdn.bootcss.com/1000hz-bootstrap-validator/0.9.0/validator.min.js"></script>
{% block afterjs %}{% endblock %}
</body>
</html>

templates/index.html
{% extends "base.html" %}{% load staticfiles %}
{% block body %}
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <a class="navbar-brand" href="/"><img height="20px"
                                          src="/static/img/webzmap.png"
                                          style="padding-left: 3px; padding-top: 1px"/></a>
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
            <li><a href="/api">REST API</a></li>
            <li><a href="/admin">Admin</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'core:logout' %}"><span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>Logout </a></li>
            <li></li>
        </ul>
    </div>
</nav>


<div class="container">
    <h1>WebZmap</h1>
    <div class="row">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-12">
                    <button type="button" class="btn btn-primary pull-right" data-toggle="modal"
                            data-target="#newJobModal">New Job
                    </button>
                </div>
            </div>
            <hr>
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Name</th>
                        <th>Progress</th>
                        <th>Status</th>
                        <th>Hit</th>
                        <th>Hit Rate</th>
                        <th>Left Time</th>
                        <!--<th>Operation</th>-->
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody id="tableBody">
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<!-- New Job Modal -->
<div class="modal fade" id="newJobModal" tabindex="-1" role="dialog" aria-labelledby="newJobModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="newJobModalLabel">New Job</h4>
            </div>
            <div class="modal-body">
                <form id="newJobForm">
                    <div class="form-group">
                        <label for="inputName">Job Name</label>
                        <input type="text" class="form-control" id="inputName" placeholder="Job Name" name="name">
                    </div>
                    <div class="form-group">
                        <label for="inputPort">Target Port</label>
                        <input type="text" class="form-control" id="inputPort" placeholder="Port" name="port">
                        <p class="help-block">Example: 80</p>
                    </div>
                    <div class="form-group">
                        <label for="inputSubnets">Subnets</label>
                        <input type="text" class="form-control" id="inputSubnets" placeholder="Subnets" name="subnets">
                        <p class="help-block">Example: 192.168.0.0/16 10.0.0.0/16</p>
                    </div>
                    <div class="form-group">
                        <label for="inputBandwidth">bandwidth</label>
                        <input type="text" class="form-control" id="inputBandwidth" placeholder="Bandwidth"
                               name="bandwidth" value="1">
                    </div>
                    <div class="form-group">
                        <label for="selectWhiteListFile">White List File</label>
                        <select class="form-control" id="selectWhiteListFile" name="white_list_file">
                            <option>Ketchup</option>
                            <option>Relish</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="selectBlackListFile">Black List File</label>
                        <select class="form-control" id="selectBlackListFile" name="black_list_file">
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="selectBlackListFile">Verbosity Level</label>
                        <select class="form-control" id="selectVerbosity" name="verbosity">
                            <option value="0">FATAL</option>
                            <option value="1">ERROR</option>
                            <option value="2">WARN</option>
                            <option value="3" selected>INFO</option>
                            <option value="4">DEBUG</option>
                            <option value="5">TRACE</option>
                        </select>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="createJobButton" onclick="createJob()">Create</button>
            </div>
        </div>
    </div>
</div>

<!-- Delete Job Modal -->
<div class="modal fade" id="deleteJobModal" tabindex="-1" role="dialog" aria-labelledby="deleteJobModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="deleteJobModalLabel">Delete Job</h4>
            </div>
            <div class="modal-body">
                Are you sure you want to delete this Job?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button class="btn btn-danger" id="deleteButton">Delete</button>
            </div>
        </div>
    </div>
</div>

<!-- Log Modal -->
<div class="modal fade" id="logModal" tabindex="-1" role="dialog" aria-labelledby="logModalLabel">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="logModalLabel">Log</h4>
            </div>
            <div class="modal-body">
                <pre id="logContainer"></pre>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block afterjs %}
<script charset="UTF-8" src="{% static 'js/template.js' %}"></script>
<script id="jobRow" type="text/html">{% verbatim %}
<tr id="{{job.id}}">
    <th scope="row">{{index+1}}</th>
    <td id="{{job.id}}-name">{{job.name}}</td>
    <td>
        <div class="progress">
            <div class="progress-bar progress-bar-default progress-bar-striped {{if job.status==1}} active{{/if}}"
                 role="progressbar" aria-valuenow="job.percent_complete"
                 aria-valuemin="0" aria-valuemax="100" style="width: {{job.percent_complete}}%" id="{{job.id}}-progress">
            </div>
        </div>
    </td>
    <td id="{{job.id}}-status">{{if job.status == 0}}<span class="label label-default">Pending</span>
        {{else if job.status == 1}}<span class="label label-info">Running</span>
        {{else if job.status == 2}}<span class="label label-success">Done</span>
        {{else if job.status == 3}}<span class="label label-danger">Error</span>
        {{else if job.status == 4}}<span class="label label-warning">Paused</span>
        {{else if job.status == 5}}<span class="label label-warning">Stopped</span>
        {{else if job.status == 6}}<span class="label label-warning">Canceled</span>
        {{/if}}
    </td>
    <td id="{{job.id}}-hit">{{job.recv_success_total}}</td>
    <td id="{{job.id}}-hitRate">{{job.recv_success_total/job.sent_total | percentFormat }} </td>
    <td id="{{job.id}}-left">
        {{if job.status==1}}{{job.time_remaining | readableTime}}{{else}}-{{/if}}
    </td>
    <!--<td>-->
        <!--{{if job.status==1}}-->
        <!--<button type="button" class="btn btn-default"><span class="glyphicon glyphicon-pause" id="{{job.id}}-operation" onclick="createCommand('{{job.url}}', 0)"></span></button>-->
        <!--{{else if job.status == 4}}-->
        <!--<button type="button" class="btn btn-default"><span class="glyphicon glyphicon-play" id="{{job.id}}-operation" onclick="createCommand('{{job.url}}', 1)"></span></button>-->
        <!--{{else}}-->
        <!--<button type="button" class="btn btn-default"><span class="glyphicon glyphicon-repeat" id="{{job.id}}-operation"></span></button>-->
        <!--{{/if}}-->
    <!--</td>-->
    <td>
        <a href="/static/{{job.id}}/output.txt"
           class="btn btn-sm btn-default"  id="{{job.id}}-download"><span class="glyphicon glyphicon-download" aria-hidden="true"></span>Download</a>
        <button type="button" class="btn btn-sm btn-default" {{if job.status== 0}}disabled="disabled" {{ /if}} onclick="showLog('{{job.id}}')" id="{{job.id}}-log">Log</button>
        <button type="button" class="btn btn-sm btn-danger" onclick="showDeleteJobModal('{{job.url}}')"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></button>
    </td>
</tr>{% endverbatim %}
</script>
<script id="statusTemplate" type="text/html">{% verbatim %}
{{if status == 0}}<span class="label label-default">Pending</span>
{{else if status == 1}}<span class="label label-info">Running</span>
{{else if status == 2}}<span class="label label-success">Done</span>
{{else if status == 3}}<span class="label label-danger">Error</span>
{{else if status == 4}}<span class="label label-warning">Paused</span>
{{else if status == 5}}<span class="label label-warning">Stopped</span>
{{else if status == 6}}<span class="label label-warning">Canceled</span>
{{/if}}
{% endverbatim %}
</script>
<script id="fileOption" type="text/html">{% verbatim %}
<option value="{{file.value}}">{{file.display_name}}</option>{% endverbatim %}
</script>
<script charset="UTF-8" src="{% static 'js/app.js' %}"></script>
{% endblock %}

templates/login.html
{% extends "base.html" %}{% load staticfiles %}
{% block title %}Login - WebZmap{% endblock %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="text-center title">
            <img width="55%" class="paper" src="{% static 'img/webzmap.png' %}"/>
        </div>
        <div class="col-md-4 col-sm-offset-4 col-sm-4 col-sm-offset-4">
            <div class="panel panel-default">
                <!--<div class="panel-heading"><h1>WebZmap Login</h1></div>-->
                <div class="panel-body">
                    {% if error %}<div class="alert alert-danger">{{error}}</div>{% endif %}
                    <form action="{% url 'core:login' %}" method="post">
                        {% csrf_token %}
                        <input hidden="hidden" name="next" value="{{next}}">
                        <div class="form-group">
                            <label for="inputUsername">Username</label>
                            <input type="text" class="form-control" id="inputUsername" placeholder="Username"
                                   name="username" autofocus>
                        </div>
                        <div class="form-group">
                            <label for="inputPassword">Password</label>
                            <input type="password" class="form-control" id="inputPassword" placeholder="Password"
                                   name="password">
                        </div>
                        <button type="submit" class="btn btn-default">Login</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}